# Workflow name
name: Create Chrome Extension Release

# This workflow runs only when a new tag matching 'v*.*.*' is pushed.
on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build-and-release:
        # Use the latest Ubuntu runner.
        runs-on: ubuntu-latest

        # Grant permissions for the GITHUB_TOKEN to create a release.
        permissions:
            contents: write

        steps:
            # Step 1: Check out the repository's code.
            - name: Checkout repository
              uses: actions/checkout@v4

            # Step 2: Set up the Bun environment.
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            # Step 3: Install project dependencies.
            - name: Install dependencies
              run: bun install

            # Step 4: Run the build script for the Chrome extension.
            - name: Build Chrome Extension
              run: bun run build:chrome

            # Step 5: Package the 'dist_chrome' directory into a zip file.
            - name: Package extension
              run: zip -r extension.zip dist_chrome

            # Step 6: Create a new GitHub Release.
            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  body: New release for tag ${{ github.ref_name }}
                  draft: false
                  prerelease: false

            # Step 7: Upload the zipped extension as a release asset.
            - name: Upload Release Asset
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./extension.zip
                  asset_name: extension-${{ github.ref_name }}.zip
                  asset_content_type: application/zip
